### ISSUE TITLE
please use `osmojs` instead of `@cosmology/core`

### ISSUE THREAD

**Issue by pyramation** [mars-protocol/multichain-liquidator-bot#65]
https://github.com/mars-protocol/multichain-liquidator-bot/blob/15d462c6f84c34a66852aa33e68566ef71dfea34/liquidator/package.json#L24

Hi! Cosmology/core is becoming deprecated soon, as the asset list is "baked in" and the code is legacy. 

An ideal workflow is to use `osmojs` and `@osmonauts/math`, which we have [examples as shown here](https://github.com/cosmology-tech/create-cosmos-app/tree/main/examples/swap-tokens) and in a [video/tweet here](https://twitter.com/cosmology_tech/status/1657044367738130433?s=20)

then you can use the `chain-registry` for loading assets, and you can use `@chain-registry/osmosis` for pre-baked assets, or `@chain-registry/utils` to build an asset list dynamically:

```
import { ibc, assets } from 'chain-registry';
import { getAssetLists } from '@chain-registry/utils';

const list = getAssetLists('osmosis', ibc, assets);
```

**Comment by wolfmark152** [comment]
this is random but maybe you can help me ... have atom/staked atom farm position on mars hub.  i can't close position i keep getting 404 error and will not load the page. lost almost 50 percent of value in last two days

**Comment by markonmars** [comment]
hey @wolfmark152 the [mars protocol discord](https://discord.marsprotocol.io/) is the best place for those kind of issues, if you are still facing the issue you described ask there any they should be able to help you 👍
